Initial commit.
LittleGizen/study-unit-tests pull request #1
Opened 2024-09-20 14:49 UTC by LittleGizen

Added structure and files with logic for homework.

2024-09-23 10:36 UTC, Alexandr056 requested changes
сложная и спорная реализация, давайте проще:
один проход всех методов и валидация аннотаций, раскладываем по кучкам

далее если все ок, то вызываем их

2024-09-23 10:36 UTC, Alexandr056 commented on src/main/java/ru/innotech/study/TestRunner.java
> +        Arrays.stream(c.getMethods()).forEach(method -> annotationList.addAll(List.of(method.getDeclaredAnnotations())));
создаете стрим (все методы класса, перебираем и собираем в список аннотаций, все аннотации представленные на методе?) причем каждый метод, а аннотации в одну кучу? зачем?

стрим в отдельный объект не выделяете, терминальной операии нет

2024-09-23 10:36 UTC, Alexandr056 commented on src/main/java/ru/innotech/study/TestRunner.java
> +        Arrays.stream(c.getMethods()).forEach(method -> {
еще перебор методов…

2024-09-23 10:36 UTC, Alexandr056 commented on src/main/java/ru/innotech/study/TestRunner.java
> +        annotationList.forEach(annotation -> {
отдельно проходить все что бы проверить только диапазон значений от 0 до 10 избыточно

2024-09-23 10:36 UTC, Alexandr056 commented on src/main/java/ru/innotech/study/TestRunner.java
> +        annotationList.forEach(annotation -> {
снова перебор аннотаций
собираете имена отдельно?

что-то очень сложная конструкция

2024-09-24 19:33 UTC, LittleGizen commented on src/main/java/ru/innotech/study/TestRunner.java
> +        Arrays.stream(c.getMethods()).forEach(method -> annotationList.addAll(List.of(method.getDeclaredAnnotations())));
Думал, что forEach терминальный. 
Поправил.

2024-09-24 19:33 UTC, LittleGizen commented on src/main/java/ru/innotech/study/TestRunner.java
> +        Arrays.stream(c.getMethods()).forEach(method -> {
Убрал.

2024-09-24 19:33 UTC, LittleGizen commented on src/main/java/ru/innotech/study/TestRunner.java
> +        annotationList.forEach(annotation -> {
Поправил.

2024-09-24 19:33 UTC, LittleGizen commented on src/main/java/ru/innotech/study/TestRunner.java
> +        annotationList.forEach(annotation -> {
Убрал.

2024-09-24 19:34 UTC, LittleGizen commented
> сложная и спорная реализация, давайте проще: один проход всех методов и валидация аннотаций, раскладываем по кучкам
> 
> далее если все ок, то вызываем их

Чуть упростил конструкцию.

2024-09-25 07:38 UTC, Alexandr056 approved these changes
хорошая работа над ошибками, есть еще пара комментариев, но работа хорошая и сейчас достаточно для того что бы ее принять. ок

2024-09-25 07:38 UTC, Alexandr056 commented on src/main/java/ru/innotech/study/TestRunner.java
> +    public void runTests(Class c) throws NoSuchMethodException, InvocationTargetException, IllegalAccessException, InstantiationException {
можно схлопнуть до Exception

2024-09-25 07:38 UTC, Alexandr056 commented on src/main/java/ru/innotech/study/TestRunner.java
> +            System.err.printf("Annotation %s priority out of range (1-10) in method %s.\n", Test.class, method);
а приложение дальше будет работать? просто напишет что ошибка? 
здесь место для исключения

2024-09-25 07:38 UTC, Alexandr056 commented on src/main/java/ru/innotech/study/TestRunner.java
> +            System.err.printf("Method %s marked with %s but not static.\n", method, annotationClass);
аналогично

2024-09-30 07:38 UTC, merged